colors:
    ROBOT_PERFORMING_TASK: [255, 255, 0]
    ROBOT_NOT_PERFORMING_TASK: [0, 255, 0]
    BRINGUP_NOT_RUNNING: [255, 255, 255]
    COMPONENTS_WORKING: [0, 255, 0]
    COMPONENTS_NOT_WORKING: [255, 0, 0]
    E_STOP_PRESSED: [255, 0, 0]
    LOW_BATTERY: [255, 0, 0]
    MEDIUM_BATTERY: [255, 255, 0]
    HIGH_BATTERY: [0, 255, 0]
    BLACK: [0, 0, 0]
brightness: 20
